


resources:
  repositories:
  - repository: yamlfiles
    type: git
    name: test/yamlfiles

trigger:
  branches:
    include:
      - master

pool: 
  name: SelfHostedKO
  demands: 
  - agent.name: s3

name: Provisioning VCP cluster nodes
workspace:
  clean: all

pool:
  vmImage: 'ubuntu-18.04'

variables:
  system.debug: true

steps:
- checkout: self
  clean: true
  persistCredentials: true
- checkout: yamlfiles
  path:test/yamlfiles
  persistCredentials: true
 -checkout: git://test/yamlfiles
  persistCredentials: true
  
